# 02.TensorFlow Ops

### 처음 만나는 텐서플로 프로그램

In [1]:
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(x))

/Users/JunChangWook/anaconda2/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


5


해당 머신에서는 아래와 같은 에러 발생 하지 않음   
Warning?
The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.


<b> 개선 방안 

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(x))

5


<b> TensorBoard로 시각화하기

In [4]:
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    # writer = tf.summary.FileWriter('./graphs', sess.graph) 
    print(sess.run(x))
writer.close() # 사용하여 완료되면 닫는다.

5


 터미널로 이동, 실행  
$ python3 [yourprogram].py  


$ tensorboard --logdir="./graphs" --port 6006    


브라우져로 이동해서 URL을 통해서 Open : http://localhost:6006/    

![Alt_text](./02_images/01.png)

### 상수, 시퀀스, 변수, 연산

### 상수

### tf.constant(  
###    value,  
###    dtype=None,  
###    shape=None,    
###    name='Const', 
###    verify_shape=False  
### )  

In [5]:
import tensorflow as tf
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


<b> 텐서 형상을 만들고 모든 요소는 0이 될 것입니다.

### tf.zeros(shape, dtype=tf.float32, name=None)

In [7]:
tf.zeros([2, 3], tf.int32) # [[0, 0, 0], [0, 0, 0]]

<tf.Tensor 'zeros_1:0' shape=(2, 3) dtype=int32>

<b> input_tensor로 형태의 텐서와 타입 (타입이 지정되지 않은 경우)을 생성하지만 모든 원소는 0입니다.

### tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)

In [9]:
# input_tensor is [[0, 1], [2, 3], [4, 5]]
input_tensor = tf.constant([[0, 1], [2, 3], [4, 5]], name='input_tensor')
tf.zeros_like(input_tensor) #  [[0, 0], [0, 0], [0, 0]]

<tf.Tensor 'zeros_like:0' shape=(3, 2) dtype=int32>

<b>위와 0으로 바꾸는 것을 1로 바꾸는 형태의 API

### tf.ones(shape, dtype=tf.float32, name=None)  
### tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)  

<b>스칼라 값으로 채워진 텐서를 만듭니다.

In [12]:
tf.fill([2, 3], 8) # [[8, 8, 8], [8, 8, 8]]

<tf.Tensor 'Fill_1:0' shape=(2, 3) dtype=int32>

<b> 순서적인 상수

### tf.lin_space(start, stop, num, name=None)

In [16]:
tf.lin_space(10.0, 13.0, 4) # [10. 11. 12. 13.]

<tf.Tensor 'LinSpace_2:0' shape=(4,) dtype=float32>

### tf.range(start, limit=None, delta=1, dtype=None, name='range')

In [18]:
tf.range(3, 18, 3) # [3 6 9 12 15]

<tf.Tensor 'range:0' shape=(5,) dtype=int32>

In [19]:
tf.range(5) # [0 1 2 3 4]

<tf.Tensor 'range_1:0' shape=(5,) dtype=int32>

<b>Randomly 만드는 상수

### tf.random_normal
### tf.truncated_normal
###  tf.random_uniform
### tf.random_shuffle
### tf.random_crop
### tf.multinomial
### tf.random_gamma

### tf.set_random_seed(seed)

### Operations

![Alt_text](./02_images/02.png)

# 산수 연산

![Alt_text](./02_images/03.png)

In [1]:
import tensorflow as tf

a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))             # [[0 0] [1 1]]
    print(sess.run(tf.divide(b, a)))          # [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.truediv(b, a)))         # [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.floordiv(b, a)))        # [[0 0] [1 1]]
    #print(sess.run(tf.realdiv(b, a)))         # Error: only works for real values
    print(sess.run(tf.truncatediv(b, a)))     # [[0 0] [1 1]]
    print(sess.run(tf.floor_div(b, a)))       # [[0 0] [1 1]]

/Users/JunChangWook/anaconda2/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


<b> TensorFlow는 Python 네이티브 유형 인 boolean, numeric (int, float), strings를 사용합니다.

In [2]:
t_0 = 19 # scalars are treated like 0-d tensors
tf.zeros_like(t_0) # ==> 0
tf.ones_like(t_0) # ==> 1

<tf.Tensor 'ones_like:0' shape=() dtype=int32>

In [3]:
t_1 = [b"apple", b"peach", b"grape"] # 1-d arrays are treated like 1-d tensors
tf.zeros_like(t_1) # ==> [b'' b'' b'']
#tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.

<tf.Tensor 'zeros_like_1:0' shape=(3,) dtype=string>

In [4]:
t_2 = [[True, False, False],
  [False, False, True],
  [False, True, False]]         		# 2-d arrays are treated like 2-d tensors

tf.zeros_like(t_2)                   			# ==> 3x3 tensor, all elements are False
tf.ones_like(t_2)                    			# ==> 3x3 tensor, all elements are True

<tf.Tensor 'ones_like_1:0' shape=(3, 3) dtype=bool>

<b> Tensorflow Data Type

![Alt_text](./02_images/04.png)

<b> TF vs NP Data Types 

<b> TensorFlow는 NumPy와 완벽하게 통합됩니다.

In [5]:
import tensorflow as tf
import numpy as np
tf.int32 == np.int32 # True

True

<b>TensorFlow 작업에 numpy 유형 전달 가능

In [6]:
tf.ones([2, 2], np.float32) # ⇒ [[1.0 1.0], [1.0 1.0]]

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

<b>NumPy ndarray가 출력하기

In [7]:
sess = tf.Session()
a = tf.zeros([2, 3], np.int32)
print(type(a)) # ⇒ <class 'tensorflow.python.framework.ops.Tensor'>
a = sess.run(a)
print(type(a)) # ⇒ <class 'numpy.ndarray'>
sess.close()

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [11]:
sess = tf.Session()
a = tf.zeros([2, 3], np.int32)
print(type(a))  
a = sess.run(a) 
print(type(a))
#sess.run(a) # numpy type을 돌리면 문제가 발생한다. string or Tensor를 넣으라고 한다. 
#print(type(a)) 

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


### 변수

In [1]:
import tensorflow as tf
# create variables with tf.Variable
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]), name="big_matrix")

# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

/Users/JunChangWook/anaconda2/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


tf.constant는 op  
tf.Variable은 ops가있는 클래스  

In [2]:
with tf.variable_scope("re", tf.AUTO_REUSE): # Variable 재사용을 위해서 묶어 주어야 한다. 
    # create variables with tf.get_variable
    s = tf.get_variable("scalar", initializer=tf.constant(2)) 
    m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
    W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # 초기화 하지 않고 run 해서 문제가 발생하였음
    print(W)   

<tf.Variable 're/big_matrix:0' shape=(784, 10) dtype=float32_ref>


<b>초기화 방법

In [4]:
# 모든 변수를 초기화 할때:
# with tf.Session() as sess:
# 	sess.run(tf.global_variables_initializer())

# 특정 변수를 초기화 할때:
# with tf.Session() as sess:
# 	sess.run(tf.variables_initializer([a, b]))

# 한개의 변수를 초기화 할때
# W = tf.Variable(tf.zeros([784,10]))
# with tf.Session() as sess:
# 	sess.run(W.initializer)

In [5]:
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
	sess.run(W.initializer)
	print(W)

<tf.Variable 'Variable:0' shape=(700, 10) dtype=float32_ref>


<b> 변수에 eval() 호출하기

In [6]:
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval())

[[-0.9573367   0.31823814  1.9677258  ...  0.6959151  -0.06618451
  -0.47761008]
 [ 0.9179731  -0.92240137  0.22415967 ... -1.1661531  -1.0861632
   1.0087031 ]
 [-0.04595494  0.84018826  1.7406505  ...  0.38236785  0.9499502
   0.74038607]
 ...
 [-0.6783619   1.7802242   0.3298555  ... -0.79418343  0.25208804
   0.03983775]
 [-0.07961898 -0.50160563  1.0162234  ...  1.410699    0.52315706
  -0.44471458]
 [-1.8426884  -0.08401607 -1.5757493  ... -0.22457807 -0.06775574
  -0.43082544]]


<b> tf.Variable.assign()

In [8]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval()) 

10


In [10]:
W = tf.Variable(10)
assign_op = W.assign(100) # 새로 지정하면 다른 Variable에 넣어야 한다. 
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval()) 

100


In [14]:
my_var = tf.Variable(2, name="my_var") # 선언

# 값 재 지정
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(my_var.eval()) 
    sess.run(my_var_times_two)
    print(my_var.eval()) 
    sess.run(my_var_times_two) 
    print(my_var.eval()) 
    sess.run(my_var_times_two) 
    print(my_var.eval()) 

2
4
8
16


In [16]:
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(my_var.eval()) 
    sess.run(my_var.assign_add(10)) # 더하기
    print(my_var.eval())     
    sess.run(my_var.assign_sub(2))  # 빼기 
    print(my_var.eval())     

10
20
18


In [18]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

20
8
120
-42


### tf.Graph.control_dependencies(control_inputs)

In [22]:
# 5개의 variable을 가지고 있다. : a, b, c, d, e
g = tf.get_default_graph()
#with g.control_dependencies([a, b, c]):
    #  위와 같이 순서를 정해 줄수 있다 . a b c 이후에 d e를 진행 한다. 

### tf.placeholder(dtype, shape=None, name=None)

In [24]:
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])

b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant or a variable
c = a + b  # short for tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [1, 2, 3]}))  # placeholder에는 이것처럼 주입 해줘야 한다. 

[6. 7. 8.]


<b> Graph 그리기

![Alt_text](./02_images/05.png)

<b> feed 가능 유무를 확인 하는 함수

# tf.Graph.is_feedable(tensor) 

In [33]:
# create operations, tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    # compute the value of b given a is 15
    sess.run(b, feed_dict={a: 15})
    print(b.eval()) # 45가 아닌데 흠 ...

21


<b>Normal loading

In [34]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)
writer.close()

![Alt_text](./02_images/06.png)

![Alt_text](./02_images/08.png)

<b> 한번에 그래프에 추가 된다.

<b>Lazy loading

In [36]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(tf.add(x, y)) # z를 풀어서 여기다가 넣어 놨다.
writer.close()

![Alt_text](./02_images/07.png)

![Alt_text](./02_images/09.png)

<b> 그래프에 10번 추가 된다.  안좋다.